Allow to create unlogged IMMVs
mediapart/pg_ivm pull request #1
Opened 2024-07-17 11:43 UTC by Jamal-B

## Description

In some cases (e.g. for very large IMMVs containing volatile data), and provided you are well aware of the risks or drawbacks involved, it may be useful to create an IMMV without writing to [PostgreSQL Write-Ahead Logs](https://www.postgresql.org/docs/current/wal-intro.html).

[PostgreSQL unlogged tables](https://www.postgresql.org/docs/current/sql-createtable.html#SQL-CREATETABLE-UNLOGGED) drawbacks are multiple (not replicated, not backuped, ...) but the main one to keep in mind is that they are automatically truncated after a crash or unclean shutdown. If these conditions meet your requirements, this, as with simple unlogged tables, allows to improve write performance, reduce vacuum impact, and produce less WALs (thus reducing network usage, backup size and restoration time).

I hesitated to propose this PR because allowing unlogged IMMVs goes a bit against the fact that [PostgreSQL does not allow the creation of unlogged materialized views](https://github.com/postgres/postgres/blob/05ffe9398b758bbb8d30cc76e9bbc638dab2d477/src/backend/parser/analyze.c#L3050-L3060). But since this feature (based on the fact that IMMVs are, under the hood, classical PostgreSQL tables feeded by triggers) is very useful in our case, I thought that it could also be the same for some other users of this superb tool that is pg_ivm. 

Please note that I am not a C developer, and I would obviously be happy to consider your comments related to the code... or, of course, the feature itself.

## Tests

```sql
select create_immv('test_immv_1', 'select 1');
select create_immv('test_immv_2', 'select 1', true);
select create_immv('test_immv_3', 'select 1', false);

select relname, relpersistence
from   pg_class
where  relname ~ 'test_immv_';
```
```
   relname   | relpersistence 
-------------+----------------
 test_immv_1 | p
 test_immv_2 | p
 test_immv_3 | u
```

2024-07-17 12:14 UTC, desbouis commented on pg_ivm--1.0.sql
> +CREATE FUNCTION create_immv(text, text, boolean)
Il ne faut pas juste ajouter le `boolean` ?
On en avait parlé, mais maintenant que je vois le code, je trouve étrange de déclarer 2 fonctions du même nom qui référencent le même module, j'ai l'impression que la seconde écrase la première...

2024-07-17 13:07 UTC, Jamal-B commented on pg_ivm--1.0.sql
> +CREATE FUNCTION create_immv(text, text, boolean)
La seconde n'écrase pas la première car dans postgresql les fonctions sont polymorphes, elles peuvent prendre plusieurs nombres et types de paramètres différents :
```sql
create function test(text, text) returns integer language sql return 1;
create function test(text, integer) returns integer language sql return 1;
create function test(integer, text) returns integer language sql return 1;
create function test(boolean, boolean, text) returns integer language sql return 1;

\df test*
/*
                        List of functions
 Schema | Name | Result data type |  Argument data types   | Type 
--------+------+------------------+------------------------+------
 public | test | integer          | boolean, boolean, text | func
 public | test | integer          | integer, text          | func
 public | test | integer          | text, integer          | func
 public | test | integer          | text, text             | func
*/
```

Mais suite à ta remarque j'ai quand même (re)fait un test que je pensais avoir bien fait, à savoir, définir une valeur par défaut pour le troisième paramètre booléen s'il n'est pas passé lors de l'appel à la fonction. Je pensais que ça n'était pas possible en PL/pgSQL car j'ai confondu avec la partie du code en C, langage pour lequel j'avais vu que les paramètres des procédures et fonctions ne pouvaient pas prendre de valeur par défaut, contrairement à C++ et C# (même si bizarrement je n'ai pas rencontré de pb sur cette partie-là :thinking:).

J'ai poussé [un fixup](https://github.com/mediapart/pg_ivm/pull/1/commits/19f91dbff040d1c9dbbe11e7832edaa24ef3c741) qui ne contient plus qu'une fonction `create_immv()`. Les tests (faits après recompilation + drop/create extension) restent concluants :
```sql
select create_immv('test_immv_1', 'select 1');
select create_immv('test_immv_2', 'select 1', true);
select create_immv('test_immv_3', 'select 1', false);

select relname, relpersistence
from   pg_class
where  relname ~ 'test_immv_';
```
```
   relname   | relpersistence 
-------------+----------------
 test_immv_1 | p
 test_immv_2 | p
 test_immv_3 | u
```

2024-07-17 13:26 UTC, desbouis commented
il y a aussi une typo là https://github.com/mediapart/pg_ivm/pull/1/commits/89a36db16511d3c25f017f297951619244c6fad4#diff-deba2a349774e214152c698e2877e9a4559ba454d7b418a3471ab3bbd993efe3R113

2024-07-17 13:34 UTC, desbouis approved these changes

2024-07-17 13:45 UTC, Jamal-B commented
> il y a aussi une typo là
> 
> https://github.com/mediapart/pg_ivm/blob/89a36db16511d3c25f017f297951619244c6fad4/createas.c#L113

Merci ! Corrigée et squashée ! Mais je crois que je vais m'arrêter là ... je veux empêcher maître Capello de passer sur tous les fichiers du projet pour corriger leurs anciennes typos :slightly_smiling_face:

2024-07-17 13:45 UTC, desbouis commented on createas.c
> +		into->rel->relpersistence = RELPERSISTENCE_UNLOGGED;
En fait, j'ai un doute...
Pourquoi la persistence n'est pas plutôt définie dans ce blochttps://github.com/mediapart/pg_ivm/blob/89a36db16511d3c25f017f297951619244c6fad4/pg_ivm.c#L219-L227 avec le reste, ce qui ne ferait pas changer la signature de `ExecCreateImmv` ?

2024-07-17 13:56 UTC, Jamal-B commented on createas.c
> +		into->rel->relpersistence = RELPERSISTENCE_UNLOGGED;
C'est ce que j'avais essayé de faire dans un premier temps (je vous en avais parlé en daily mais je raconte tellement de trucs que ... :wink:) mais ça n'avait pas fonctionné car pg_ivm crée d'abord une vraie vue matérialisée qu'il transforme ou remplace ensuite par la (vraie) table finale. Et si j'essaie de définir le unlogged dans la portion de code que tu pointes, donc au niveau de la première vue, j'obtiens l'erreur postgresql suivante :
```
select create_immv('test_immv_1', 'select 1');
ERROR:  materialized views cannot be unlogged
```

2024-07-17 15:08 UTC, desbouis commented on createas.c
> +		into->rel->relpersistence = RELPERSISTENCE_UNLOGGED;
ah oui ok, peut-être à cause du `Assert(is_matview);` juste au-dessus...

2024-07-17 15:52 UTC, coox commented on pg_ivm--1.0.sql
> +CREATE FUNCTION create_immv(text, text, boolean default true)
Je pense que ce fichier est immuable !

La logique de migration voudrait que ta fonction avec la signature modifiée soit entièrement redéclarée dans un fichier `pg_ivm--1.8--1.9.sql`, avec : 

```sql
CREATE OR REPLACE FUNCTION create_immv(text, text, boolean default true)
```

2024-07-17 15:54 UTC, coox commented on README.md
> +create_immv(immv_name text, view_definition text [, is_immv_logged bool]) RETURNS bigint
C'est drôle parce qu'en tant qu'utilisateur de pg_ivm, et connaissant ton intention, je me serais attendu à une fonction munie de la logique inverse (car reprenant la terminologie PostgreSQL).

Et aussi, je pense que c'est important de référencer dans les docs la valeur par défaut.

Ça donnerait quelque chose comme :

```sql
create_immv(immv_name text, view_definition text [, unlogged bool DEFAULT false]) RETURNS bigint
```

2024-07-17 15:55 UTC, coox commented
Outre mes deux commentaires ci-dessus, je trouve le reste nickel, les docs sont excellentes, et je suis globalement hyper heureux que cette PR existe 🎉

2024-07-17 16:14 UTC, desbouis commented on pg_ivm--1.0.sql
> +CREATE FUNCTION create_immv(text, text, boolean default true)
ah mais oui...
Je n'avais pas fait attention, mais ces fichiers correspondent effectivement aux releases de pg_ivm...
Il est aussi à référencer dans https://github.com/mediapart/pg_ivm/blob/main/Makefile#L17

2024-07-17 16:17 UTC, desbouis requested changes
je retire mon :heavy_check_mark:  pour le coup de la release ;-)

2024-07-19 16:00 UTC, Jamal-B commented on createas.c
> +		into->rel->relpersistence = RELPERSISTENCE_UNLOGGED;
On en a déjà parlé à l'oral hier, mais non ce n'est pas à cause du `Assert(is_matview);` qui est en effet là pour vérifier qu'à ce stade l'objet initialement créé est bien une vraie vue matérialisée, mais qui est placé juste après l'endroit où survient l'erreur si on essaie d'appliquer la propriété *unlogged* sur l'objet (qui n'est remplacé que plus tard dans le code par le nouvel objet qui lui est bien une table, qu'on peut rendre *unlogged*).

2024-07-19 16:00 UTC, Jamal-B commented on pg_ivm--1.0.sql
> +CREATE FUNCTION create_immv(text, text, boolean default true)
Bien vu @coox !!! ... et j'ai honte de ne pas y avoir fait attention car, comme je vous en parlais sur Mattermost, un ou deux jours avant d'ouvrir la PR (que j'avais en fait préparée depuis assez longtemps), j'avais aussi identifié le côté immuable de ces fichiers en cherchant le fameux [event trigger](https://github.com/sraoss/pg_ivm/blob/main/pg_ivm--1.0.sql#L44-L66) de nettoyage de la table `pg_catalog.pg_ivm_immv` qui avait été remplacé dans la version 1.3 par des [object_access_hook](https://github.com/sraoss/pg_ivm/pull/29) ayant nécessité [cette suppression](https://github.com/sraoss/pg_ivm/pull/29/commits/405196e07eff8aed8a7bc5cce2be9de58265ff10#diff-852bda3552680014cdf71322c14946e2730e101a7a7c076dbf1d0ad454bc03bb).

2024-07-19 16:00 UTC, Jamal-B commented on README.md
> +create_immv(immv_name text, view_definition text [, is_immv_logged bool]) RETURNS bigint
> C'est drôle parce qu'en tant qu'utilisateur de pg_ivm, et connaissant ton intention, je me serais attendu à une fonction munie de la logique inverse (car reprenant la terminologie PostgreSQL).
> 
> Et aussi, je pense que c'est important de référencer dans les docs la valeur par défaut.
> 
> Ça donnerait quelque chose comme :
> 
> ```sql
> create_immv(immv_name text, view_definition text [, unlogged bool DEFAULT false]) RETURNS bigint
> ```

Très bonne remarque de l'amiral !!!
Pour l’historique, cette version contraire à la logique et sans la valeur par défaut dans la doc est due à ce que j'expliquais à David dans [ce commentaire](https://github.com/mediapart/pg_ivm/pull/1#discussion_r1681021336). Et croyant à tord que je devais ajouter la nouvelle fonction à côté de la précédente (et non à la place), et estimant qu'elle était spécifiquement là pour la création d'IMMVs unlogged, ça m'avait paru naturel que `true` soit synonyme de "je veux que mon IMMV soit unlogged" (même si en effet ça se discute). Mais c'est vrai qu'au moment de ne garder qu'une seule fonction avec le troisième paramètre non obligatoire, j'aurais dû avoir la rigueur de revoir ça (valeur par défaut à false + l'indiquer dans la doc).
Merci pour ta vigilance :+1:

2024-07-19 16:00 UTC, Jamal-B commented
> Outre mes deux commentaires ci-dessus, je trouve le reste nickel, les docs sont excellentes, et je suis globalement hyper heureux que cette PR existe (…bientôt dans le repo officiel 😉) 🎉

Merci :smile:

2024-07-19 16:02 UTC, Jamal-B commented
> je retire mon ✔️ pour le coup de la release ;-)

J'ai poussé [un fixup](https://github.com/mediapart/pg_ivm/pull/1/commits/e67f3aaa2bb6976aff01f0c22e09dfd2f6c8fdc2) qui prend en compte vos remarques et j'ai mis à jour la description de la PR avec les tests refaits avec la nouvelle version (le comportement du false devient celui du true et réciproquement).

2024-07-19 16:18 UTC, coox approved these changes
🔥

2024-07-19 16:23 UTC, desbouis commented
Je pense qu'il faut faire un commit à part qui se nomme `Prepare 1.9`  en y mettant tout ce qui touche au bump de version, en s'insirant de https://github.com/mediapart/pg_ivm/commit/9736c8c832588553c2d13008223b52272a07a44b

2024-07-22 07:43 UTC, COil approved these changes
Quelques NIP de typos à appliquer ou pas (rien de méchant).

2024-07-22 07:43 UTC, COil commented on README.md
> +In some cases (e.g. for very large IMMVs containing volatile data), and only if you really know what you are doing, it may be useful to create an IMMV without writing to the [PostgreSQL Write-Ahead L
allow to improve  > improve

2024-07-22 07:43 UTC, COil commented on README.md
> +In some cases (e.g. for very large IMMVs containing volatile data), and only if you really know what you are doing, it may be useful to create an IMMV without writing to the [PostgreSQL Write-Ahead L
NIP :
less > fewer

2024-07-22 07:43 UTC, COil commented on README.md
> +In such situation, we can use `refresh_immv` function with `with_data = false` to disable immediate maintenance before modifying a base table. After a base table modification, call `refresh_immv`with
In such situation > In such a situation
we can use `refresh_immv` > we can use the `refresh_immv`

2024-07-22 07:43 UTC, COil commented on createas.c
> +	 * SEE THE POSTGRESQL DOCUMENTATION FOR DRAWBACKS (not replicated or included in physical backups, truncated in case of crash, ...):
of crash > of a crash

2024-07-22 07:53 UTC, Jamal-B commented
> Je pense qu'il faut faire un commit à part qui se nomme `Prepare 1.9` en y mettant tout ce qui touche au bump de version, en s'insirant de [9736c8c](https://github.com/mediapart/pg_ivm/commit/9736c8c832588553c2d13008223b52272a07a44b)

Le :monocle_face: d'or en encore frappé ! Et là encore j'ai honte, parce qu'évidemment quand j'avais commencé à bosser sur le sujet j'avais bien vu tous les commits `Prepare <version>` ! Encore faut-il brancher son cerveau quand c'est nécessaire ! Shame on me!
J'ai poussé une version corrigée et tassée.

2024-07-22 08:06 UTC, desbouis approved these changes

2024-07-22 08:23 UTC, Jamal-B commented on README.md
> +In such situation, we can use `refresh_immv` function with `with_data = false` to disable immediate maintenance before modifying a base table. After a base table modification, call `refresh_immv`with
Merci pour la remarque mais je préfère laisser tel quel car ce ne sont pas des erreurs importantes/gênantes/structurantes et qu'elles ne proviennent pas de mes commits. Dans le 1er commit j'ai bien corrigé des typos qui étaient déjà dans le projet, mais uniquement car elles concernaient des noms de fonctions.

2024-07-22 08:23 UTC, Jamal-B commented on README.md
> +In some cases (e.g. for very large IMMVs containing volatile data), and only if you really know what you are doing, it may be useful to create an IMMV without writing to the [PostgreSQL Write-Ahead L
Celles-ci sont les miennes :smile: Corrigées ! Merci !

2024-07-22 08:30 UTC, Jamal-B commented on README.md
> +In such situation, we can use `refresh_immv` function with `with_data = false` to disable immediate maintenance before modifying a base table. After a base table modification, call `refresh_immv`with
Dit autrement, je ne voudrais pas trop distraire le(s) mainteneur(s) avec autre chose que le but principal de cette PR, dont je ne suis pas du tout sûr qu'elle soit acceptée :slightly_smiling_face:

2024-07-22 08:32 UTC, Jamal-B commented on createas.c
> +	 * SEE THE POSTGRESQL DOCUMENTATION FOR DRAWBACKS (not replicated or included in physical backups, truncated in case of crash, ...):
Idem, prise en compte dans le dernier fixup.

2024-07-22 13:09 UTC, Jamal-B commented
:heart: Merci pour vos reviews !
:arrow_right: [PR](https://github.com/sraoss/pg_ivm/pull/91) identique créée dans le repo du projet.
:warning: Je ne merge pas celle-là chez nous pour le moment car :
1. @loliee veut y jeter un œil (merci !)
2. si ma PR était acceptée dans le repo du projet, je me demande s'il ne vaudrait pas mieux complètement supprimer celle-ci pour éviter les divergences ou galères de réconciliation. D'ailleurs dans ce cas, notre fork n'aurait de toute façon plus de raison d'être.

2024-07-22 13:16 UTC, loliee approved these changes

2024-07-23 10:56 UTC, Jamal-B commented
J'ai complété les tests qui se trouvent dans la description de la PR (ici et celle du repo d'origine).

2025-03-20 13:12 UTC, desbouis commented on pg_ivm--1.9--1.10.sql
> +CREATE FUNCTION create_immv(text, text, boolean default false)
faut pas mettre `true` ici aussi par défaut ?

2025-03-21 13:59 UTC, Jamal-B commented on pg_ivm--1.9--1.10.sql
> +CREATE FUNCTION create_immv(text, text, boolean default false)
Mais bien sûr que oui ! Et surtout il faut faire la modif là et pas dans `pg_ivm.c` comme j'ai d'abord essayé de le faire. Et puis d'abord pourquoi tu traînes ici ? La PR est en WIP pour le moment :wink:  Mais merci ! :slightly_smiling_face:

2025-03-21 14:26 UTC, desbouis commented on pg_ivm--1.9--1.10.sql
> +CREATE FUNCTION create_immv(text, text, boolean default false)
je traïne ici parce que j'ai été notifié tiens :-)

2025-04-07 09:04 UTC, Jamal-B commented
Closing this PR, replaced by #2.

2025-04-07 09:04 UTC, closed without merging